name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]        

    steps:
    - uses: browser-actions/setup-chrome@latest
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci    
    - run: export DISPLAY=:99.0
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ./ #optional
        run: npm test
   # - run: sh -e /etc/init.d/xvfb start
    - run: npm i -g karma # info - http://karma-runner.github.io/0.8/plus/Travis-CI.html
    - run: npm i -g cat
    - run: npm i rxjs
    - run: npm run test:all
